package com.agriculture.AgroPlanner.constants;

public class ColumnNames {
    public static final String USER_USERID = "userID";
    public static final String USER_USERNAME = "user_name";
    public static final String USER_PASSWORD = "password";
    public static final String USER_MAIL = "mail";
    public static final String LOCATION = "location";
    public static final String LOCATION_LATITUDE = "latitude";
    public static final String LOCATION_LONGITUDE = "longitude";
    public static final String TASK_TASKID = "taskID";
    public static final String TASK_TASKNAME = "name";
    public static final String TASK_TASKDESC = "description";
    public static final String TASK_DUEDATE = "due_date";
    public static final String TASK_STATUS = "status";
    public static final String TASK_USERID = "userID";
    public static final String TASK_COMPLETE = "Complete";
    public static final String TASK_NOT_COMPLETE = "Not Complete";
    public static final String FINANCIAL_RECORD_RECORDID = "recordID";
    public static final String FINANCIAL_RECORD_DATE = "date";
    public static final String FINANCIAL_RECORD_TYPE = "type";
    public static final String FINANCIAL_RECORD_AMOUNT = "amount";
    public static final String FINANCIAL_RECORD_DESC = "description";
    public static final String FINANCIAL_RECORD_USERID = "userID";
    public static final String FINANCIAL_RECORD_INCOME = "Income";
    public static final String FINANCIAL_RECORD_EXPENSE = "Expense";
    public static final String FINANCE_STATS = "Financial Statistics";
    public static final String FINANCE_STATS_TOTAL_INCOME = "totalIncome";
    public static final String FINANCE_STATS_TOTAL_EXPENSES = "totalExpenses";
    public static final String FINANCE_STATS_AVERAGE_INCOME = "averageIncome";
    public static final String FINANCE_STATS_AVERAGE_EXPENSE = "averageExpense";
    public static final String FINANCE_STATS_MAX_INCOME = "maxIncome";
    public static final String FINANCE_STATS_MAX_EXPENSE = "maxExpense";
    public static final String FINANCE_STATS_MIN_INCOME = "minIncome";
    public static final String FINANCE_STATS_MIN_EXPENSE = "minExpense";
    public static final String EMPLOYEE_EMPLOYEEID = "employeeID";
    public static final String EMPLOYEE_FIRSTNAME = "first_name";
    public static final String EMPLOYEE_LASTNAME = "last_name";
    public static final String EMPLOYEE_CONTACTINFO = "contact_info";
    public static final String EMPLOYEE_ROLE = "role";
    public static final String EMPLOYEE_SALARY = "salary";
    public static final String EMPLOYEE_USERID = "userID";
    public static final String CROP_CROPID = "cropID";
    public static final String CROP_NAME = "name";
    public static final String CROP_SPECIES = "species";
    public static final String CROP_PLANTING_DATE = "planting_date";
    public static final String CROP_HARVEST_DATE = "harvest_date";
    public static final String CROP_DESCRIPTION = "description";
    public static final String CROP_REQUIREMENTS = "requirements";
    public static final String HARVEST_ENTRY_EMPLOYEEID = "employeeID";
    public static final String HARVEST_ENTRY_CROPID = "cropID";
    public static final String HARVEST_ENTRY_QUANTITY = "quantity_kg";
    public static final String HARVEST_ENTRY_DATE = "date";
    public static final String HARVEST_ENTRY_NOTES = "notes";
    public static final String CROP_STATS = "Harvest Statistics";
    public static final String CROP_STATS_QUANTITY = "cropQuantity";
    public static final String CROP_STATS_TOTAL = "totalYield";
    public static final String CROP_STATS_AVERAGE = "averageYield";
    public static final String CROP_STATS_MAX_CROP = "maxYieldCrop";
    public static final String CROP_STATS_MIN_CROP = "minYieldCrop";
    public static final String INVENTORY_ITEMID = "itemID";
    public static final String INVENTORY_NAME = "name";
    public static final String INVENTORY_QUANTITY = "quantity";
    public static final String INVENTORY_PRICE = "price";
    public static final String INVENTORY_EMPLOYEEID = "employeeID";


}
